name: CI/CD Frontend Innovatech
on:
  push:
    branches: [ "main" ]
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verificar identidad AWS
        run: aws sts get-caller-identity

      - name: Verificar clúster ECS
        run: aws ecs list-clusters

      - name: Verificar servicios ECS
        run: aws ecs list-services --cluster ${{ secrets.ECS_CLUSTER_NAME }}
